import type { AssembledDocument, DocSection } from "./model";
import { STATE_NAMES } from "@/lib/interview/states";
import { ATTORNEY_REVIEW_REQUIRED } from "@/lib/legal";
import { perspective, isCouple, type AssembleOpts } from "./couples";
import { selfProvingAffidavitFor } from "./clauses/self-proving-affidavit";
import { needsAttorneyReview } from "./clause-provenance";

/*
 * ⚠️ [ATTORNEY REVIEW REQUIRED] — Every clause below is PLACEHOLDER language for
 * engineering the assembler. It is NOT final legal text. Conditional inclusion
 * is driven by the normalized StateRuleset + interview answers (data-driven),
 * never by hardcoded state codes.
 */

const s = (v: unknown) => (typeof v === "string" ? v.trim() : "");
const list = <T>(v: unknown): T[] => (Array.isArray(v) ? (v as T[]) : []);

type Child = { name?: unknown; isMinor?: unknown };
type Beneficiary = { name?: unknown; percent?: unknown };
type Bequest = { item?: unknown; recipient?: unknown };

function ordinalWitnessWord(n: number): string {
  return n === 2 ? "two (2)" : `${n}`;
}

export function assembleWill(opts: AssembleOpts): AssembledDocument {
  const { answers, ruleset } = opts;
  const about = answers.about ?? {};
  const family = answers.family ?? {};
  const fid = answers.fiduciaries ?? {};
  const dist = answers.distributions ?? {};
  const special = answers.special ?? {};
  const ancillary = answers.ancillary ?? {};

  const couple = isCouple(opts);
  // For a couple, each spouse's will is generated from one shared interview:
  // "self" is this will's testator, "spouseName" is the other spouse.
  const { self: signerName, other: spouseName } = perspective(
    answers,
    opts.signer ?? "primary",
  );
  const stateName = STATE_NAMES[ruleset.state] ?? ruleset.state;
  const children = list<Child>(family.children);
  const minorChildren = children.filter((c) => c.isMinor === true);
  const beneficiaries = list<Beneficiary>(dist.beneficiaries);
  const bequests = list<Bequest>(dist.specificBequests);

  const sections: DocSection[] = [];

  // --- Notice (draft watermark) ---
  sections.push({
    heading: "Notice",
    paragraphs: [
      `${ATTORNEY_REVIEW_REQUIRED} This is a self-help draft generated by My Defender Will & Trust. It is not legal advice and has not been reviewed by an attorney. We strongly recommend having a licensed attorney in ${stateName} review this document before signing.`,
    ],
  });

  // --- Declaration ---
  sections.push({
    heading: "Article I — Declaration",
    paragraphs: [
      `I, ${signerName}, a resident of ${stateName}, being of sound mind, declare this to be my Last Will and Testament, and I revoke all prior wills and codicils.`,
    ],
  });

  // --- Family ---
  const familyParas: string[] = [];
  const maritalStatus = s(about.maritalStatus);
  const spouse = s(family.spouseName);
  if (couple) {
    familyParas.push(`I am married to ${spouseName}.`);
  } else if (maritalStatus === "married" && spouse) {
    familyParas.push(`I am married to ${spouse}.`);
  } else if (maritalStatus) {
    familyParas.push(`My marital status is: ${maritalStatus}.`);
  }
  if (children.length) {
    familyParas.push(
      `I have the following children: ${children.map((c) => s(c.name)).filter(Boolean).join(", ")}.`,
    );
  } else {
    familyParas.push("I have no children.");
  }
  sections.push({ heading: "Article II — Family", paragraphs: familyParas });

  // --- Executor (couples name each other, with the shared alternate) ---
  const execParas: string[] = [];
  if (couple) {
    execParas.push(
      `I appoint my spouse, ${spouseName}, as the Executor (personal representative) of this Will.`,
    );
    const altExec = s(fid.executorAlt) || s(fid.executorName);
    if (altExec) {
      execParas.push(
        `If my spouse is unable or unwilling to serve, I appoint ${altExec} as alternate Executor.`,
      );
    }
  } else {
    execParas.push(
      `I appoint ${s(fid.executorName) || "[Executor]"} as the Executor (personal representative) of this Will.`,
    );
    if (s(fid.executorAlt)) {
      execParas.push(
        `If that person is unable or unwilling to serve, I appoint ${s(fid.executorAlt)} as alternate Executor.`,
      );
    }
  }
  sections.push({ heading: "Article III — Executor", paragraphs: execParas });

  // --- Guardian (only if minor children) ---
  if (minorChildren.length && s(fid.guardianName)) {
    const gParas = [
      `If a guardian is needed for my minor child(ren), I appoint ${s(fid.guardianName)} as guardian.`,
    ];
    if (s(fid.guardianAlt)) {
      gParas.push(`If that person cannot serve, I appoint ${s(fid.guardianAlt)} as alternate guardian.`);
    }
    sections.push({ heading: "Article IV — Guardian for Minor Children", paragraphs: gParas });
  }

  // --- Distributions ---
  const distParas: string[] = [];
  if (bequests.length) {
    distParas.push("I make the following specific gifts:");
    for (const b of bequests) {
      distParas.push(`• ${s(b.item)} to ${s(b.recipient)}.`);
    }
  }
  if (couple) {
    distParas.push(
      `I give my entire residuary estate to my spouse, ${spouseName}, if my spouse survives me.`,
    );
    if (beneficiaries.length) {
      distParas.push(
        "If my spouse does not survive me, I give my residuary estate as follows:",
      );
      for (const b of beneficiaries) {
        distParas.push(`• ${s(String(b.percent))}% to ${s(b.name)}.`);
      }
    }
  } else if (beneficiaries.length) {
    distParas.push("I give my residuary estate as follows:");
    for (const b of beneficiaries) {
      distParas.push(`• ${s(String(b.percent))}% to ${s(b.name)}.`);
    }
  }
  // Per stirpes / per capita — data-driven from the answer.
  if (dist.distributionType === "per_stirpes") {
    distParas.push(
      "If any beneficiary does not survive me, that beneficiary's share shall pass to their descendants, per stirpes.",
    );
  } else if (dist.distributionType === "per_capita") {
    distParas.push(
      "If any beneficiary does not survive me, that beneficiary's share shall be divided among the surviving beneficiaries, per capita.",
    );
  }
  if (s(dist.charitable)) distParas.push(`Charitable gifts: ${s(dist.charitable)}`);
  if (s(dist.disinheritance)) distParas.push(`I intentionally make no provision for: ${s(dist.disinheritance)}.`);
  sections.push({ heading: "Article V — Disposition of Property", paragraphs: distParas });

  // --- Community property acknowledgment (data-driven) ---
  if (ruleset.communityProperty) {
    sections.push({
      heading: "Article VI — Community Property",
      paragraphs: [
        `${stateName} is a community property state. This Will disposes only of my separate property and my one-half interest in community property, and is not intended to affect my spouse's interest in community property. ${ATTORNEY_REVIEW_REQUIRED}`,
      ],
    });
  }

  // --- Special provisions ---
  const specialParas: string[] = [];
  const minorAge = s(special.minorTrustAge);
  if (minorAge) {
    specialParas.push(
      `Any property passing to a beneficiary under age ${minorAge} shall be held in trust until that beneficiary reaches age ${minorAge}.`,
    );
  }
  if (special.petCare === true) {
    specialParas.push(`Pet care: ${s(special.petCareDetail) || "I direct that my pets be cared for as provided herein."}`);
  }
  if (special.digitalAssets === true) {
    specialParas.push("My Executor shall have authority over my digital assets and online accounts to the extent permitted by law.");
  }
  if (special.noContest === true) {
    specialParas.push("No-contest clause: any beneficiary who contests this Will shall forfeit their share, to the extent enforceable under applicable law.");
  }
  if (specialParas.length) {
    sections.push({ heading: "Article VII — Special Provisions", paragraphs: specialParas });
  }

  // --- Ancillary references ---
  const ancParas: string[] = [];
  if (couple) {
    ancParas.push(`A separate Durable Financial Power of Attorney appoints my spouse, ${spouseName}, as my agent.`);
    ancParas.push(`A separate Healthcare Directive appoints my spouse, ${spouseName}, as my healthcare agent.`);
    ancParas.push("A separate HIPAA authorization is included with this package.");
  } else {
    if (s(ancillary.financialPoaAgent)) ancParas.push(`A separate Durable Financial Power of Attorney appoints ${s(ancillary.financialPoaAgent)}.`);
    if (s(ancillary.healthcareAgent)) ancParas.push(`A separate Healthcare Directive appoints ${s(ancillary.healthcareAgent)}.`);
    if (ancillary.hipaaAuthorize === true) ancParas.push("A separate HIPAA authorization is included with this package.");
  }
  if (ancParas.length) {
    sections.push({ heading: "Article VIII — Related Documents", paragraphs: ancParas });
  }

  // --- Attestation (witness count + signature-at-end, data-driven) ---
  const attestation: string[] = [];
  const nWit = ordinalWitnessWord(ruleset.witnessesRequired);
  attestation.push(
    ruleset.signatureAtEndRequired
      ? `I sign this Will at the end, on the date written below, in the presence of ${nWit} witnesses.`
      : `I sign this Will on the date written below in the presence of ${nWit} witnesses.`,
  );
  attestation.push(
    `The foregoing instrument was signed by ${signerName} and declared to be their Last Will, and we, ${nWit} witnesses${ruleset.witnessMinAge ? ` (each at least ${ruleset.witnessMinAge} years old)` : ""}, signed in the presence of the testator and each other.`,
  );
  sections.push({ heading: "Attestation", paragraphs: attestation });

  // --- Self-proving affidavit (data-driven; researched text where available) ---
  // Resolved per state from the clause library. States with researched, cited
  // text (see clauses/self-proving-affidavit.ts) get language drafted against
  // that state's statute; every other state falls through to the conservative
  // placeholder. Either way the text stays flagged for counsel until approved.
  // Signature/notary block contributed by a researched clause, when there is one.
  let clauseSignatureLines: string[] | null = null;
  if (ruleset.selfProvingAffidavit.available === true) {
    const clause = selfProvingAffidavitFor(ruleset.state, {
      testatorName: signerName,
      stateName,
      witnessCount: ruleset.witnessesRequired,
      requiresNotary: ruleset.selfProvingAffidavit.requiresNotary,
    });
    const paragraphs = [...clause.paragraphs];
    if (needsAttorneyReview(clause.provenance)) {
      paragraphs.push(
        clause.provenance.status === "researched"
          ? `${ATTORNEY_REVIEW_REQUIRED} This affidavit is drafted to track ${clause.provenance.citation} and has not yet been approved by an attorney.`
          : `${ATTORNEY_REVIEW_REQUIRED} (${ruleset.selfProvingAffidavit.requiresNotary ? `Notarization required in ${stateName}.` : `${stateName} may permit an unsworn declaration in lieu of notarization.`})`,
      );
    }
    sections.push({ heading: "Self-Proving Affidavit", paragraphs });
    // A researched clause supplies its own statute-specific execution block
    // (notary wording, commission line, seal); prefer it over the generic block.
    if (clause.provenance.status === "researched") {
      clauseSignatureLines = clause.signatureLines;
    }
  } else if (ruleset.selfProvingAffidavit.available === "uncertain") {
    sections.push({
      heading: "Self-Proving Affidavit",
      paragraphs: [
        `${ATTORNEY_REVIEW_REQUIRED} Self-proving affidavit availability in ${stateName} requires attorney confirmation and is omitted from this draft.`,
      ],
    });
  }

  // --- Signature lines (data-driven witness count + optional notary) ---
  const signatureLines: string[] = [`Testator: ${signerName}`, "Date"];
  for (let i = 1; i <= ruleset.witnessesRequired; i++) {
    signatureLines.push(`Witness ${i} — signature / printed name / address`);
  }
  if (clauseSignatureLines) {
    // Statute-specific execution block from the researched clause. Skip lines
    // already emitted above so the testator/witnesses are not duplicated.
    const seen = new Set(signatureLines);
    for (const line of clauseSignatureLines) {
      if (!seen.has(line)) signatureLines.push(line);
    }
  } else if (
    ruleset.selfProvingAffidavit.available === true &&
    ruleset.selfProvingAffidavit.requiresNotary
  ) {
    signatureLines.push("Notary Public");
  }

  return {
    kind: "will",
    title: `Last Will and Testament of ${signerName}`,
    state: ruleset.state,
    signerName,
    sections,
    signatureLines,
    attorneyReviewRequired: true,
  };
}
